### ISSUE TITLE
Error: undefined method `jasperserver' for #<Rails:: ...

### ISSUE THREAD

**Issue by forbov** [cmckni3/rails-jasperserver#1]
Here is my controller:

    class ReportsController < ApplicationController
      require 'jasperserver-rails'
  
      def index
        @council_report = CouncilReport.find(params[:council_report_id])
      end

      def run_report(report_name, report_id)
        JasperserverRails::Jasperserver.new.run_report report_name + '.pdf' do
          format 'pdf'
          report report_name
          params({ :council_report_id => report_id.to_s })
        end
      end

      def proposed_works_summary
        @council_report = CouncilReport.find(params[:council_report_id])
        run_report('cams/proposed_works_summary', @council_report)
      end
    end

Everything else is as per the usage instructions. What am I missing?

**Comment by cmckni3** [comment]
I believe you're missing the initializer in `config/initializers`.

**Comment by cmckni3** [comment]
I updated the README with the instructions for setting up the initializer and config file.

**Comment by cmckni3** [comment]
@forbov Did you solve this issue?
