### ISSUE TITLE
Feature: Download report

### ISSUE THREAD

**Issue by erlinis** [cmckni3/rails-jasperserver#12]
Hello, I am using this gem in order to connect a rails app to a jasper server.
I noticed the behaviour of the `run_report` method is to create a file on the rails' app path, it is ok but it isn't what I desire, I want the hability to download a file so I forked the repository and added a [download_report method](
https://github.com/erlinis/rails-jasperserver/commit/404ded8926031b8f8c75263936e073c9b0c6e45f) and I used like this on my app:

```ruby
def machine_report
  machine_id = params[:id]
  filename = 'machines' 
  file = JasperserverRails::Jasperserver.new.download_report filename do
    format 'pdf'
    report "reports/#{filename}"
    params({ :machine_id => machine_id})
  end
  render_report(file, filename)    
end
```

```ruby
def render_report(file, name)                                                                                 
   fullpath = File.expand_path(file.path) 
   send_file(fullpath, filename: "#{name}.pdf", type: 'application/pdf')
end  
```

so far it works, please take a look and let me know what you think. In other hand I am not familiar with the tool that you used to test the features, `VCR cassette`. 
There's any simpler way to test or any easy way to learn VCR?

**Comment by cmckni3** [comment]
Sorry, totally missed this issue. I am working on a Docker setup for Jasperserver for this project.

Can you create a pull request for this?

**Comment by erlinis** [comment]
Actually I will close this issue, I followed the suggestion of @nicwillemse on [this thread](https://github.com/erlinis/rails-jasperserver/commit/47e0ed645bf71a62cb2e876403137057b101285d#commitcomment-2363518) and it worked !!

I think it would be worth add that suggestion to the Readme so it can be useful for others.

**Comment by cmckni3** [comment]
Got it. I added the sample to the readme.
