### ISSUE TITLE
Rails 5 Compatibility 

### ISSUE THREAD

**Issue by nicwillemse** [cmckni3/rails-jasperserver#9]
It appears this gem will not work be supported against rails 5, any plan to fix this ?

**Comment by cmckni3** [comment]
@nicwillemse I can fix it. Do you know why it doesn't work with Rails 5?

I can create a sample project with Rails 5 beta 3 and investigate.

**Comment by nicwillemse** [comment]
@cmckni3 I have already fixed already, please see the associated PR

**Comment by cmckni3** [comment]
I created a Rails 5 project and can add the gem to it. I'm setting up a server with jasperserver to be able to try out actual reports.

**Comment by cmckni3** [comment]
Closed with #10
